### ISSUE TITLE
Installing Python modules for import in the service script 

### ISSUE THREAD

**Issue by aspence** [torfsen/python-systemd-tutorial#14]
This is a fantastic tutorial thank you! I have a quick question:

What is the correct way to install Python packages so that they can be imported in the service python script under the dedicated service user?

E.g., i'd like to import gpustat or pySMART inside the Python script, but I believe it says module not found, no doubt because conda or pip had installed those packages in my normal user environment.

Thank you!

**Comment by Olegt0rr** [comment]
1. Install requirements to venv
2. Give permissions to venv for your service user

**Comment by aspence** [comment]
Awesome thank you Oleg - do i need to log into service user account to set this venv up, or can I create the venv under another user and then point the service script to it by choice of /usr/bin/python etc? cheers

**Comment by aspence** [comment]
Basically - how do I ensure when systemd calls the script as the service user the venv is activated?

**Comment by aspence** [comment]
Got it... TY
https://stackoverflow.com/questions/37211115/how-to-enable-a-virtualenv-in-a-systemd-service-unit
