### ISSUE TITLE
Difference between this and https://github.com/torfsen/service

### ISSUE THREAD

**Issue by jgwinner** [torfsen/python-systemd-tutorial#7]
Hi

I've been looking at https://github.com/torfsen/service, and then I found this note.

Is the main difference between this tutorial and the tutorial at https://python-service.readthedocs.io/en/stable/ control via console commands?

If someone just needs a service to automatically run, is there a reason to use https://github.com/torfsen/service?

I think a paragraph mentioning why this totorial would be used over the other tutorial (at readthedocs.io) would be great!

Thank you

**Comment by torfsen** [comment]
https://github.com/torfsen/service is a Python package and is different from this tutorial here. It is intended for writing services "manually", i.e. without the help of systemd (which was not always available on all Linux distributions). If you can use systemd (which, nowadays, you can on most distributions) then you can completely skip the `service` package and instead simply follow this tutorial.

**Comment by jgwinner** [comment]
Thank you!
